version: '3.7'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4563-4584:4563-4584'
      - '8080:8080'
    privileged: true
    environment:
      - SERVICES=s3,sqs,lambda,logs,iam,cloudwatch
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      # - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=ap-southeast-2
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - AWS_DEFAULT_REGION=ap-southeast-2
      - DB_CONNECT='postgresql://testuser:testpass@localhost:5432/testdb'
      - QUEUE_NAME=dev-queue
      - FUNCTION_NAME=dev-lambda
      - PKG_PATH=/tmp/lambdas/lambda_package.zip      
    volumes:
      - ./initlocalstack/create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh   
      # - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
