version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - 6432:5432
    volumes:
      - ./initdb/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      TZ: 'Australia/Sydney'
      PGTZ: 'Australia/Sydney'
