version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4584:4563-4584'
      - '8080:8080'
    privileged: true
    environment:
      - SERVICES=s3,sqs,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=ap-southeast-2
      - LAMBDA_EXECUTOR=docker-reuse
      # - LAMBDA_REMOTE_DOCKER=false
    volumes:
      # - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  initlocalstack:
    build:
      context: .
      dockerfile: ./initlocalstack/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - MAX_WAIT_SEC=10
      - AWS_DEFAULT_REGION=ap-southeast-2
      #- BUCKET_NAME=dev-bucket
      - QUEUE_NAME=dev-queue.fifo
      - FUNCTION_NAME=dev-lambda
      - PKG_PATH=/tmp/lambdas/lambda_package.zip
    volumes:
      - ./initlocalstack/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./initlocalstack/src:/tmp/src
      - ./lambdas/lambda_package.zip:/tmp/lambdas/lambda_package.zip
    depends_on:
      - localstack
  #     - postgres
  # postgres:
  #   image: postgres
  #   ports:
  #     - 6432:5432
  #   volumes:
  #     - ./initdb/scripts:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_USER: testuser
  #     POSTGRES_PASSWORD: testpass
  #     TZ: 'Australia/Sydney'
  #     PGTZ: 'Australia/Sydney'
